hyperparameters :
  BUFFER_SIZE : 100000
  BATCH_SIZE : 64
  GAMMA : 0.99
  TAU : 0.001
  LR : 0.0005
  UPDATE_EVERY : 4
  device : "cpu"

trainingparameters :
  n_episodes: 2000
  max_t: 1000
  eps_start: 1.0
  eps_end: 0.01
  eps_decay: 0.995